### ISSUE TITLE
Trips are not recorded

### ISSUE THREAD

**Issue by yasushisakai** [yasushisakai/hansel#2]
Trips seems not to be recorded on firebase

**Comment by tkawahar** [comment]
登録されている動画とスマホ自身のIDから、情報は下記。
- Private ID: 4b7ee897-86d7-400c-a5ce-fa6fb92ad7b2
- Trip ID: -LLijjSeLXgkl0-iv8rt

Trip ID の動画をダウンロードして撮影日時を確認すると
- time.struct_time(tm_year=2018, tm_mon=9, tm_mday=6, tm_hour=12, tm_min=0, tm_sec=57, tm_wday=3, tm_yday=249, tm_isdst=-1)

ETC⇒UTCに変換すると、4時間差し引いて 09-06-2018 08:00.57 が撮影開始時間。
これをエポック時間に変換すると
- 1536235257000

この時間は、Private ID: 4b7ee897-86d7-400c-a5ce-fa6fb92ad7b2 のbreadcrumbs 開始 (1536236323679) より前になる。
